### PR TITLE
API v3 Updates

### PR DESCRIPTION
**Pull request by synacktic**
I updated the project to work with Habitica API v3 while trying to make as few changes as possible to your code. 

The biggest change is the URI builder. Since /user/tasks is now /tasks/user, but (for example) /user/status is only /status, I added an elif to check if the request is for a task. While doing that, I made the URI build out a section at a time instead of repeating (self.auth['url'], API_URI_BASE) each time.

Still, this is a tiny change and the rest are even smaller and very obvious. 

Here is the Habitica page discussing the task layout and return data changes:
http://devs.habitica.com/api-v2-v3-migration-guide/

I did not touch the error reporting, there did not seem to be much anyway.

### CODE REVIEW

**Comment by passuf** [comment]
Thanks for your changes, I am using this fork and everything works fine!

**Comment by robertpateii** [comment]
Hi @philadams,

I just started using your command line tool for habitica thanks to synacktic's fix for v3 and it's great. Would you have a look at merging this so other people don't need to dig into the PRs? 

thanks,

Rob

**Comment by gustiando** [comment]
@philadams any way you could merge this one in? It looks like this has been working for quite a few of us. This is a really cool CLI for Habitica and I wish to continue using and seeing contributions to it :D thanks!

**Comment by philadams-zz** [comment]
Thanks @synacktic - taking a look now. Apologies on the wait, glad your fork is working well for folk.

**Comment by philadams-zz** [comment]
lgtm - merged. I'll push the new pip package after I look at the other PRs

**Comment by philadams-zz** [comment]
Thank you very much!

**Comment by synacktic** [comment]
No problem. Thanks for making the initial project for me to modify. ;) 
Sorry about the status / party error, I'm in a party and did not bother to check anything outside of one.

**Comment by philadams-zz** [comment]
No worries! Thanks for your PR, super useful.

I really need to get back to prioritizing fun side projects like this one :)

**Pull request merged**
